const { withAndroidManifest, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// bcv.org.ve's server sends the wrong/legacy intermediate certificate (a
// server misconfiguration, verified with `openssl s_client` — the leaf cert's
// issuer is "Sectigo Public Server Authentication CA DV R36" but the server
// actually sends "Sectigo RSA Domain Validation Secure Server CA" instead).
// iOS's NSURLSession tolerates this (chases the correct intermediate via a
// cached/AIA lookup); Android's OkHttp does not, and fetch() fails with a
// generic "Network request failed". Fix: bundle the correct intermediate
// (fetched from the leaf cert's own AIA URL, crt.sectigo.com) as an extra
// trust anchor scoped to just this domain, via Android's network security
// config — this is regenerated by `expo prebuild`, so it must live in a
// config plugin rather than a hand-edited native file (android/ is gitignored).
const CERT_SOURCE = path.join(__dirname, "certs", "bcv-sectigo-intermediate.pem");
// Setting android:networkSecurityConfig makes Android ignore the debug
// manifest's usesCleartextTraffic="true" (used so the app can reach Metro's
// dev server over plain HTTP) — API 24+ prefers this config over that flag
// once both are present. Re-declare the same dev-server exception here,
// scoped to just those hosts, instead of opening cleartext broadly.
const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">10.0.2.2</domain>
    </domain-config>
    <domain-config>
        <domain includeSubdomains="true">bcv.org.ve</domain>
        <trust-anchors>
            <certificates src="@raw/bcv_sectigo_intermediate" />
            <certificates src="system" />
        </trust-anchors>
    </domain-config>
</network-security-config>
`;

function withBcvNetworkSecurityConfig(config) {
  return withDangerousMod(config, [
    "android",
    async (config) => {
      const rawDir = path.join(
        config.modRequest.platformProjectRoot,
        "app/src/main/res/raw"
      );
      const xmlDir = path.join(
        config.modRequest.platformProjectRoot,
        "app/src/main/res/xml"
      );
      fs.mkdirSync(rawDir, { recursive: true });
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.copyFileSync(
        CERT_SOURCE,
        path.join(rawDir, "bcv_sectigo_intermediate.pem")
      );
      fs.writeFileSync(
        path.join(xmlDir, "network_security_config.xml"),
        NETWORK_SECURITY_CONFIG
      );
      return config;
    },
  ]);
}

function withBcvManifestAttribute(config) {
  return withAndroidManifest(config, (config) => {
    const application = config.modResults.manifest.application[0];
    application.$["android:networkSecurityConfig"] = "@xml/network_security_config";
    return config;
  });
}

module.exports = function withBcvCertFix(config) {
  config = withBcvNetworkSecurityConfig(config);
  config = withBcvManifestAttribute(config);
  return config;
};
