// Curated Ionicons glyphs shared by the account and category icon pickers,
// grouped by theme so the picker stays a single browsable grid.
export const ICON_GROUPS: { title: string; icons: string[] }[] = [
  {
    title: "Comida",
    icons: [
      "restaurant-outline",
      "cafe-outline",
      "pizza-outline",
      "fast-food-outline",
      "wine-outline",
      "beer-outline",
      "ice-cream-outline",
      "nutrition-outline",
      "fish-outline",
      "restaurant",
      "cafe",
      "pizza",
      "cart-outline",
      "cart",
      "basket-outline",
      "gift-outline",
    ],
  },
  {
    title: "Transporte",
    icons: [
      "car-outline",
      "bus-outline",
      "train-outline",
      "bicycle-outline",
      "boat-outline",
      "subway-outline",
      "car-sport-outline",
      "airplane-outline",
      "car",
      "bus",
      "bicycle",
      "boat",
      "walk-outline",
      "navigate-outline",
      "speedometer-outline",
      "compass-outline",
    ],
  },
  {
    title: "Hogar",
    icons: [
      "home-outline",
      "key-outline",
      "flash-outline",
      "wifi-outline",
      "flame-outline",
      "business-outline",
      "hammer-outline",
      "construct-outline",
      "water-outline",
      "bed-outline",
      "home",
      "bulb-outline",
    ],
  },
  {
    title: "Salud",
    icons: [
      "heart-outline",
      "medkit-outline",
      "medical-outline",
      "flask-outline",
      "happy-outline",
      "shield-checkmark-outline",
      "cut-outline",
      "fitness-outline",
      "pulse-outline",
      "heart",
      "bandage-outline",
    ],
  },
  {
    title: "Educación",
    icons: [
      "school-outline",
      "library-outline",
      "ribbon-outline",
      "book-outline",
      "football-outline",
      "pencil-outline",
      "calculator-outline",
      "musical-notes-outline",
    ],
  },
  {
    title: "Tecnología",
    icons: [
      "phone-portrait-outline",
      "call-outline",
      "play-circle-outline",
      "laptop-outline",
      "desktop-outline",
      "wifi-outline",
      "game-controller-outline",
      "tv-outline",
    ],
  },
  {
    title: "Finanzas",
    icons: [
      "cash-outline",
      "card-outline",
      "swap-horizontal-outline",
      "wallet-outline",
      "trending-up-outline",
      "trending-down-outline",
      "bar-chart-outline",
      "calculator-outline",
    ],
  },
  {
    title: "Entretenimiento",
    icons: [
      "sparkles-outline",
      "film-outline",
      "shirt-outline",
      "basketball-outline",
      "gift-outline",
      "musical-notes-outline",
      "barbell-outline",
      "game-controller-outline",
    ],
  },
  {
    title: "Trabajo",
    icons: [
      "briefcase-outline",
      "hammer-outline",
      "cube-outline",
      "paper-plane-outline",
      "laptop-outline",
      "document-text-outline",
      "people-outline",
      "ellipsis-horizontal-outline",
    ],
  },
];
